### PR TITLE
Fix/single package json refactor

### PR DESCRIPTION
**Pull request by Oliversw**
So! It was _slightly_ terrifying, but I think I did manage to refactor the project. Doing so also got rid of the problem that was coming up between the server copy of Jest and Create React App. 

That said, the changes to the file structure is pretty massive so I wanted to put this up for discussion first! There are also likely some bugs in there somewhere seeing as this touched most of the code, so the more eyes on it the better! I'd also love if someone could look over the eslintrc.json as I had to merge the two and wasn't sure about some of the rules.

Also if we do want to go ahead with this it will affect the work that you're doing now, so I wanted to make sure that we had everything merged that we wanted to so I could fix the conflicts, push it up, and then we could all continue from there.

Looking forward to hearing what y'all think!

### CODE REVIEW

**Comment by Oliversw** [comment]
Just so it's recorded somewhere, I message @oliverjam about it and he said this about his opinion on multiple package.jsons: 

> so that's definitely possible, but it can end up being a bit of a pain. You can treat both directories as entirely separate (with their own dependencies etc), but then they might as well be separate git repos too
> Generally if you want to run multiple packages in a monorepo something like Yarn Workspaces is a good idea. It helps you manage the multiple sets of dependencies etc
> personally unless you really need multiple packages (e.g. publishing different things to different places from the same git repo) then I'd either stick to a single root package.json or just separate git repos

**Comment by Oliversw** [comment]
Closing for now since we decided that it was better to focus on other code

**Comment by m4v15** [comment]
Hi all 👋 

Sorry I never got a chance to properly look at this, I had a very busy weekend in the end. It's also a bit hard to review as I'm not sure what the problems you were having before were and what (if any) problems arose from this fix - I spoke to @orjwan98 about it a bit tho.

Generally for using create-react-app I'd probably lean towards having 2 package-json's just because it makes it's own with its own scripts and stuff, but in other cases I'd agree with ollie that one is fine - however in my experience that package can become huge and unmanageable. Ultimately like a lot of things there's not completely right answer...

TBH tho, within a single sprint, I would just stick with whatever you started out doing, because (maybe as you found) changing it around can be complicated and confusing - if you did want to change it, I'd wait till the start of another sprint and do it before any other work gets started

**Comment by teenie-quaggard** [comment]
@m4v15 
Thank you for your advice! Much appreciated!

**Pull request closed without merging**
