### PR TITLE
Fix/responsive pages

### PR DESCRIPTION
**Pull request by Oliversw**
Made media queries and altered styles so that most pages should now also display properly on mobile and tablets as well as desktops.
Also added a constants file to hold the responsive sizes.

I still need to fix the footer as well as the form page, but since I'll have to get on the flight soon I wanted to push this up and do the rest in another branch.

Let me know  if it works for you all!

Edit May 22:
- most elements are now centered for tablets and below, as is most text (justified text just looked a little too awkward in some places that didn't have the right amount of text)
- the form has been centered, and inputs made to take most of the screen
   - Note: when editing the MUI elements I couldn't find out how to include the responsive constants file, so I put the actual px in. I included 'TODO' comments on each page to refactor it at a later date.
- the footer has been edited to display in more of a column, with larger elements
  

Issue #114

### CODE REVIEW

**Comment by orjwan98** [comment]
Okay great work @Oliversw. I love the way you structured the code but here's a couple of stuff: 

1. I personally think we should center all headings and subheadings and justify the paragraphs. Every element should be taking up 100% of the width of the screen. 
2. Maybe we should use view ports for containers like header/body/footer. 
3. You've already mentioned styling the form and footer, so nothing else to mention :)

**Comment by Oliversw** [comment]
Thanks for those suggestions @orjwan98! I have updated the PR now. 

- most elements are now centered for tablets and below, as is most text (justified text just looked a little too awkward in some places that didn't have the right amount of text)
- the form has been centered, and inputs made to take most of the screen
   - Note: when editing the MUI elements I couldn't find out how to include the responsive constants file, so I put the actual px in. I included 'TODO' comments on each page to refactor it at a later date.
- the footer has been edited to display in more of a column, with larger elements

**Comment by Oliversw** [comment]
@orjwan98 @mhmdtshref I have created a new issue that I will be working on that contains your feedback. I think it will be worth getting what's on here merged and then working on the rest.

Is there anything broken or that definitely needs to be fixed before we merge this? If not, I will merge as soon as it is approved. Thank you!!

**Comment by orjwan98** [comment]
@Oliversw aside from the issues I've mentioned, there's not anything else. Unless you pushed somehting new since the last time I reviewed :)

**Pull request merged**
